PyTorch

https://pytorch.org/docs/stable/tensors.html#

the code of install is found at   https://anaconda.org



**1.**

**torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)**

data------Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.


**torch.Tensor(...)**

参数是你想要建立张量的维数

torch.Tensor(3,4)    torch.Tensor(3,4,5)  torch.Tensor(3,)

In [0]:
import numpy as np
import torch

#create a tensor
x=torch.Tensor(3,4)
y=torch.tensor([1,2,3])
print(x)
print(y)
print(x.type(),y.type())
print(x[1,2])
print(y[1])

tensor([[2.3847e-36, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])
tensor([1, 2, 3])
torch.FloatTensor torch.LongTensor
tensor(1.3733e-14)
tensor(2)


In [0]:
#create a random tensor
x=torch.randn(2,3)
y=torch.rand(2,3)
print(x)
print(y)

tensor([[ 0.4544,  0.4066,  0.2233],
        [ 0.1510, -0.5712,  0.7280]])
tensor([[0.8550, 0.8970, 0.2678],
        [0.0030, 0.2351, 0.6155]])


In [0]:
#list
arr=torch.Tensor(np.random.rand(2,3))
x=torch.from_numpy(np.random.rand(2,3))
print(arr)
print(x)

tensor([[0.5806, 0.0777, 0.4369],
        [0.5267, 0.3833, 0.1907]])
tensor([[0.9980, 0.9118, 0.2919],
        [0.4428, 0.1536, 0.3978]], dtype=torch.float64)


In [0]:
print(arr.type())
print(x.type())

torch.FloatTensor
torch.DoubleTensor


In [0]:
aa=torch.Tensor(3,)
bb=torch.Tensor(3,1)
aa_t=torch.t(aa)
bb_t=torch.t(bb)

cc=torch.Tensor([[1,2,3],[4,5,6]])
dd=torch.Tensor(2,3)

print("aa:{0},\naa_t:{1}".format(aa.size(),aa_t.size()))
print("bb:{0},\nbb_t:{1}".format(bb.size(),bb_t.size()))
print(cc.type(),dd.type())
print(cc)
print(dd)

aa:torch.Size([3]),
aa_t:torch.Size([3])
bb:torch.Size([3, 1]),
bb_t:torch.Size([1, 3])
torch.FloatTensor torch.FloatTensor
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[4.1546e-37, 0.0000e+00, 8.4078e-45],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])


In [0]:
aa=aa.reshape(-1,1)
aa_t=torch.t(aa)
print("aa:{0},\naa_t:{1}".format(aa.size(),aa_t.size()))
print(aa)
print(aa_t)

aa:torch.Size([3, 1]),
aa_t:torch.Size([1, 3])
tensor([[2.3847e-36],
        [0.0000e+00],
        [4.4842e-44]])
tensor([[2.3847e-36, 0.0000e+00, 4.4842e-44]])


In [0]:
x=torch.Tensor(3,4)
y=x.reshape(2,6)
z=x.view(2,6)
print(x)
print(y,y.type())
print(z,z.type())

tensor([[4.1549e-37, 0.0000e+00, 4.4842e-44, 0.0000e+00],
        [       nan, 0.0000e+00, 1.6781e-07, 8.3022e-10],
        [2.5930e-09, 1.3666e+22, 1.3015e+22, 2.1532e+23]])
tensor([[4.1549e-37, 0.0000e+00, 4.4842e-44, 0.0000e+00,        nan, 0.0000e+00],
        [1.6781e-07, 8.3022e-10, 2.5930e-09, 1.3666e+22, 1.3015e+22, 2.1532e+23]]) torch.FloatTensor
tensor([[4.1549e-37, 0.0000e+00, 4.4842e-44, 0.0000e+00,        nan, 0.0000e+00],
        [1.6781e-07, 8.3022e-10, 2.5930e-09, 1.3666e+22, 1.3015e+22, 2.1532e+23]]) torch.FloatTensor


In [0]:
#gradient
x=torch.rand(3,4,requires_grad=True)
y=x**3+2
#y.backward()


In [0]:
print(x)
print("---------------------")
print(y)


tensor([[0.4244, 0.2380, 0.5275, 0.8852],
        [0.7287, 0.4686, 0.7111, 0.4911],
        [0.2487, 0.1533, 0.5413, 0.1660]], requires_grad=True)
---------------------
tensor([[2.0764, 2.0135, 2.1468, 2.6936],
        [2.3870, 2.1029, 2.3596, 2.1185],
        [2.0154, 2.0036, 2.1586, 2.0046]], grad_fn=<AddBackward0>)


In [0]:
z=y.mean()
print(z)

tensor(2.1734, grad_fn=<MeanBackward0>)


In [0]:
z.backward()
print(x.grad)

tensor([[0.0450, 0.0142, 0.0696, 0.1959],
        [0.1328, 0.0549, 0.1264, 0.0603],
        [0.0155, 0.0059, 0.0732, 0.0069]])


In [0]:
print(1/4*x*x)#equals to z.backward()


tensor([[0.0450, 0.0142, 0.0696, 0.1959],
        [0.1328, 0.0549, 0.1264, 0.0603],
        [0.0155, 0.0059, 0.0732, 0.0069]], grad_fn=<MulBackward0>)


https://www.cnblogs.com/JeasonIsCoding/p/10164948.html

In [0]:
from torch.autograd import Variable
a=Variable(torch.FloatTensor([[2.,4.]]),requires_grad=True)
b=torch.zeros(1,2)
b=a**2+1
out=2*b
out.backward(torch.FloatTensor([[1.,1.]]))
print("---------------------")
print(a.data)
print("---------------------")
print(out.data)
print("---------------------")
print(a.grad)

---------------------
tensor([[2., 4.]])
---------------------
tensor([[10., 34.]])
---------------------
tensor([[ 8., 16.]])


In [0]:
print(a.shape)

torch.Size([1, 2])


In [0]:
#gradient
aa=Variable(torch.FloatTensor([[33,44],[55,66],[6,7]]),requires_grad=True)
bb=a*3+2
bb.backward(torch.FloatTensor([[3,4],[5,5],[6,7]])) #传入的shape维度不能超过aa的shape
print(aa.data)
print(bb)
print(aa.grad)

tensor([[33., 44.],
        [55., 66.],
        [ 6.,  7.]])
tensor([[ 8., 14.]], grad_fn=<AddBackward0>)
None


In [0]:
temp=torch.FloatTensor([[3,4,4,4],[5,6,7,8],[6,7,8,9]])
print(temp.shape)

torch.Size([3, 4])


In [0]:
print(torch.cuda.is_available())

True
